# Generated by Django 4.0.5 on 2022-07-06 04:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='announcement',
        ),
        migrations.CreateModel(
            name='AnnounComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('announ_comment', models.TextField()),
                ('announ_likes', models.ManyToManyField(blank=True, related_name='announ_comment_likes', to=settings.AUTH_USER_MODEL)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announ_comments', to='app.announcement')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Announ_comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
