# Generated by Django 4.0.5 on 2022-07-06 07:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_likes_remove_comment_likes_comment_likes_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='likes_by',
            field=models.ManyToManyField(blank=True, related_name='likes_comments', through='app.Likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
